### ISSUE TITLE
Buttons style not in line with obsidian theme, especially dark scheme

### ISSUE THREAD

**Issue by Gamuxper** [shabegom/buttons#235]
Hi,

Thanks for this plugin, I really like how simple it is to fire of Quickadd Capture with it. That is something I didn't know how to do with metabind.

However, I find the styling of the button doesn't mesh well with the default obsidian style. In light scheme, I dislike the animation and shading on hover. In dark mode, the whole thing looks weird.

So I took the dafult theme color variable names from [the Default Obsidian Theme colors list](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/Default+Obsidian+Theme+Colors) and used them in my css snippet file:
```css
/* Obsidian Buttons plugin: compact dark & light theme styles */
.block-language-button > button,
.theme-dark .block-language-button > button {
    background: var(--interactive-normal);
    border-radius: 5px;
    border: 1px solid var(--interactive-accent);
    color: var(--text-accent);
    margin: 0;
    box-shadow: none;
    transform: none;
}
.block-language-button > button:hover,
.theme-dark .block-language-button > button:hover {
    background: var(--interactive-hover);
    border: 1px solid var(--interactive-accent-hover);
    color: var(--text-accent-hover);
    box-shadow: none;
    transform: none;
}
```
I changed the background, border, and text colors, got rid of shadow and transform animation. While I was at it, i changed the border radius to better match tick box radius and got rid of the margin to better align it with other stuff in my notes.

A before/after image for dark theme hover:
### Before:
![Image](https://github.com/user-attachments/assets/60da490e-f45d-4ac3-83b7-d80d8a976cba)
### After:
![Image](https://github.com/user-attachments/assets/d0e8caab-f366-4c84-8f8f-0fa893a0331c)

Major benefit is that as I use variables defined by theme, the colors will presumably be compatible with other schemes. Like those biege schemes a lot of people seem to like.

Can the maintainer change the colors used by the buttons to the variables defined by theme, and possibly get rid of the shadow and animation on hover?

Cheers,
Gamuxper
